name: Auto Sync Fork

on:
  schedule:
    # This runs the workflow every hour
    - cron: '0 * * * *'
  # You can also trigger it manually
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Team-8-Uma-2025/ConceptualZoo.git
      
      - name: Fetch upstream
        run: |
          git fetch upstream
      
      - name: Merge upstream
        run: |
          git merge upstream/main
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
